// Consolidated client-side Mudras data matching the 10-page final PDF
const mudras = [
  {
    id: "dhyana-mudra",
    num: "01",
    nameEn: "Dhyanamudra",
    nameMr: "ध्यानमुद्रा | समाधीमुद्रा",
    subtitleEn: "Meditation & Highest State of Tranquility",
    subtitleMr: "ध्यान आणि मन:शांती",
    iconType: "meditate",
    descEn: "This gesture indicates meditation or the highest state of tranquility. It represents deep concentration and introspection, forming a symbolic triangle of the Triratna.",
    descMr: "गौतम बुद्धांच्या या ध्यानमुद्रेतून ध्यान आणि मन:शांती प्रतीत होते. हातांच्या स्पर्शातून त्रिकोणी आकार तयार होतो, जो बुद्ध, धम्म आणि संघ या त्रिरत्नांचा अर्थ प्रतीत करतो.",
    practiceEn: "Practice during seated mindfulness to quiet discursive chatter and awaken inner serenity.",
    practiceMr: "दररोज १५-२० मिनिटे या मुद्रेत बसून श्वासावर लक्ष केंद्रित केल्यास मन शांत व स्थिर होते.",
    detailUrl: "dhyana-mudra.html"
  },
  {
    id: "vitarka-mudra",
    num: "02",
    nameEn: "Vitarkamudra",
    nameMr: "वितर्कमुद्रा | व्याख्यानमुद्रा",
    subtitleEn: "Teaching, Intellectual Discussion & Debate",
    subtitleMr: "उपदेश, वैचारिक चर्चा आणि वादचर्चा",
    iconType: "vitarka",
    image: "images/mudras/vitarka-mudra.png",
    descEn: "The thumb touching the index finger forms a continuous circle of understanding, representing knowledge evolving through discussion, with three fingers signifying the Triratna.",
    descMr: "या मुद्रेने उपदेश, वैचारिक चर्चा आणि संवादाचा निर्देश होतो. अंगठा आणि तर्जनी यांचा स्पर्श होऊन ज्ञानाचे अविरत चक्र तयार होते.",
    practiceEn: "Enhances clarity of thought, eloquence in communication, and intellectual sharpness.",
    practiceMr: "अभ्यास, वाचन आणि संवादात एकाग्रता व बौद्धिक स्पष्टता आणण्यासाठी आदर्श.",
    detailUrl: "vitarka-mudra.html"
  },
  {
    id: "vajramudra",
    num: "03",
    nameEn: "Vajramudra",
    nameMr: "वज्रमुद्रा | ज्ञानमुद्रा | बोधश्रीमुद्रा",
    subtitleEn: "Supreme Wisdom & Union of Realms",
    subtitleMr: "आत्मज्ञान आणि लौकिक-पारलौकिक एकात्मता",
    iconType: "wisdom",
    descEn: "Expresses the union of the spiritual and material realms. The erect index finger represents Buddha's true inner wisdom, enclosed protectively by the fist.",
    descMr: "या मुद्रेतून लौकिक आणि पारलौकिक जगाची एकात्मता दर्शवली जाते. उजव्या हाताची तर्जनी सत्य ज्ञानाचे प्रतीक असून डाव्या हाताची मूठ बाह्य जगाचे प्रतीक आहे.",
    practiceEn: "Restrains distracting passions and binds individual awareness with indestructible cosmic wisdom.",
    practiceMr: "ज्ञानाच्या मार्गातील अडथळे दूर करून अखंड एकाग्रता प्राप्त करण्यासाठी उपयुक्त.",
    detailUrl: "vajramudra.html"
  },
  {
    id: "dhammachakramudra",
    num: "04",
    nameEn: "Dhammachakramudra",
    nameMr: "धम्मचक्रमुद्रा",
    subtitleEn: "Turning the Wheel of Law & Truth",
    subtitleMr: "धम्माचे चक्र फिरवणे आणि धर्मोपदेश",
    iconType: "wheel",
    descEn: "Refers to turning the great wheel of Law through teachings, guiding the world through existence, famously depicted at Buddha's first sermon in Sarnath.",
    descMr: "धम्माचे चक्र फिरवण्याच्या कृतीचा निर्देश. गौतम बुद्धांना निर्वाण प्राप्त झाल्यानंतर सारनाथ येथे दिलेल्या पहिल्या धर्मोपदेशाचे हे पवित्र चित्रण आहे.",
    practiceEn: "Aligns intentional speech with virtuous moral conduct and cognitive illumination.",
    practiceMr: "सार्वजनिक सुसंवाद आणि ज्ञानाच्या प्रसारासाठी उपयुक्त.",
    detailUrl: "dhammachakramudra.html"
  },
  {
    id: "bhoomisparshamudra",
    num: "05",
    nameEn: "Bhoomisparshamudra",
    nameMr: "भूमीस्पर्शमुद्रा",
    subtitleEn: "Touching the Earth to Witness Truth",
    subtitleMr: "पृथ्वीला ज्ञानाची साक्षीदार मानणे",
    iconType: "earth",
    descEn: "Literally 'touching the earth', Buddha moved his right hand pointing down towards the earth as eternal witness to his steadfast truth, turning away temptation.",
    descMr: "गौतम बुद्धांनी एका हाताने जमिनीला स्पर्श करून पृथ्वी ही आपल्या ज्ञानाची साक्षीदार आहे असे दर्शविले आणि ध्यानातील सर्व अडथळे व मोह दूर केले.",
    practiceEn: "Cultivates unshakeable inner grounding, overcoming fear, doubt, and mental restlessness.",
    practiceMr: "मनातील संशय दूर करून दृढ आत्मविश्वास आणि अढळ स्थिरता मिळवण्यासाठी उत्तम.",
    detailUrl: "bhoomisparshamudra.html"
  },
  {
    id: "varadamudra",
    num: "06",
    nameEn: "Varadamudra",
    nameMr: "वरदमुद्रा",
    subtitleEn: "Charity, Compassion & Wish-Granting",
    subtitleMr: "औदार्य, करुणा आणि इच्छापूर्ती",
    iconType: "boon",
    descEn: "Shows charity and compassionate granting of wishes with an open downward palm, common in representations of Avalokiteshwara, the Bodhisattva of compassion.",
    descMr: "औदार्य किंवा करुणेच्या भावनेतून पूर्ण केल्या जाणाऱ्या इच्छांचा निर्देश. अवलोकितेश्वर या करुणाप्रधान बोधिसत्त्वांच्या मूर्तींमध्ये ही मुद्रा बहुधा आढळते.",
    practiceEn: "Opens unconditional empathy, selfless service, and emotional forgiveness.",
    practiceMr: "हृदयात करुणा, औदार्य आणि क्षमाशीलता वृद्धिंगत करण्यासाठी प्रभावी.",
    detailUrl: "varadamudra.html"
  },
  {
    id: "kaaranamudra",
    num: "07",
    nameEn: "Kaaranamudra",
    nameMr: "कारणमुद्रा",
    subtitleEn: "Subduing Negativity & Warding Off Obstacles",
    subtitleMr: "दानव, आजारपण व नकारात्मक विचारांवर मात",
    iconType: "ward",
    descEn: "Subdues negativity including demons, illness, and obstacles, holding up the hand with middle fingers folded to palm in scenes of active conquest.",
    descMr: "दानव, नकारात्मक विचार, आजारपण आणि सर्व अडथळ्यांवर मात करण्याचा निर्देश. दुष्ट शक्तींच्या निर्दालनाचे हे सामर्थ्यशाली प्रतीक आहे.",
    practiceEn: "Dispels pathogenic heaviness, mental fatigue, and anxiety loops.",
    practiceMr: "मानसिक तणावाच्या वेळी मनाला दृढ संरक्षण आणि सकारात्मक ऊर्जा मिळवून देते.",
    detailUrl: "kaaranamudra.html"
  },
  {
    id: "abhayamudra",
    num: "08",
    nameEn: "Abhayamudra",
    nameMr: "अभयमुद्रा",
    subtitleEn: "Conquest Over Fear & Divine Reassurance",
    subtitleMr: "भीती व द्वेष दूर करणे आणि साधकांसाठी संरक्षण",
    iconType: "protect",
    descEn: "Represents conquest over fear and hostility. Buddha gently raises his hand upright, symbolizing the removal of obstacles, protection, and serene peace.",
    descMr: "भीती आणि द्वेष दूर करण्याचा निर्देश. गौतम बुद्ध शांतपणे हात वर उचलून साधकांना सर्वतोपरी संरक्षण, शांतता आणि भयापासून मुक्ती देतात.",
    practiceEn: "Releases existential terror and anxiety, bestowing tranquil assurance.",
    practiceMr: "मनातील भीती व असुरक्षितता दूर करून धैर्य व शांती निर्माण करते.",
    detailUrl: "abhayamudra.html"
  },
  {
    id: "uttarabodhimudra",
    num: "09",
    nameEn: "Uttarabodhimudra",
    nameMr: "उत्तरबोधी मुद्रा",
    subtitleEn: "Highest Enlightenment & Inner Light",
    subtitleMr: "ज्ञानप्राप्तीची सर्वोच्च स्थिती",
    iconType: "supreme",
    descEn: "Represents the highest enlightenment. Fingers of both hands intertwined with index fingers stretched upward, frequently seen in Buddha Vairochana.",
    descMr: "या मुद्रेने ज्ञानप्राप्तीच्या सर्वोच्च स्थितीचा निर्देश केला जातो. दोन्ही हातांची बोटे गुंफून तर्जनी वर जोडल्या जातात, जी वैरोचन बुद्धांमध्ये दिसते.",
    practiceEn: "Channels vital prana, dissolves dualistic conflict, and aligns highest cosmic insight.",
    practiceMr: "प्राणायाम आणि सर्वोच्च एकाग्रतेसाठी अत्यंत प्रभावी ध्यानमुद्रा.",
    detailUrl: "uttarabodhimudra.html"
  },
  {
    id: "anjalimudra",
    num: "10",
    nameEn: "Anjalimudra",
    nameMr: "अंजलीमुद्रा | नमस्कारमुद्रा",
    subtitleEn: "Reverence, Salutation & Union of Realities",
    subtitleMr: "नमस्कार, आदर आणि लौकिक-पारलौकिक एकरूपत्व",
    iconType: "namaste",
    descEn: "Indicates reverence and homage to the teacher, while uniting spiritual and material, static and dynamic realms as palms meet at the heart.",
    descMr: "नमस्कार आणि आदराचा निर्देश. गुरूच्या शब्दांप्रती आदर दर्शविणे तसेच लौकिक आणि पारलौकिक, स्थिर आणि गतिशील जगाचे एकरूपत्व यातून व्यक्त होते.",
    practiceEn: "Balances cerebral polarities, establishing grateful humility and heartfelt connection.",
    practiceMr: "ध्यानाची सुरुवात आणि सांगता करताना मन शांत, नम्र व कृतज्ञ करण्यासाठी आदर्श.",
    detailUrl: "anjalimudra.html"
  }
];
